# -*- coding: utf-8 -*-
"""Graficas Agrupadas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXvLl5kSRyEdD-X_jp3coMOA_AUeUFNo
"""

import pandas as pd

DFT1 = pd.read_csv('/content/sample_data/SEPSISLABEL_PACIENTES.csv', index_col=0)
DFSepsis = DFT1

DFT2 = pd.read_csv('/content/sample_data/Temp_PACIENTES.csv', index_col=0)
DFTemp = DFT2.T

DFT3 = pd.read_csv('/content/sample_data/Resp_PACIENTES.csv', index_col=0)
DFResp = DFT3

DFT4 = pd.read_csv('/content/sample_data/O2sat_PACIENTES.csv', index_col=0)
DFO2sat = DFT4

DFT5 = pd.read_csv('/content/sample_data/MAP_PACIENTES.csv', index_col=0)
DFMap = DFT5

DFT6 = pd.read_csv('/content/sample_data/HR_PACIENTES.csv', index_col=0)
DFHR = DFT6

DFT7 = pd.read_csv('/content/sample_data/Glucose_PACIENTES.csv', index_col=0)
DFGlucose = DFT7

DFHR

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

fig = plt.figure(figsize=(15,15))
fig.tight_layout()
plt.ylabel('Escala') # Titulo Y
plt.xlabel('Horas') # Titulo X
plt.title("O2sat") # Titulo grafica

x1 = DFO2sat['P1']
x2 = DFO2sat['P2']
x3 = DFO2sat['P3']
x4 = DFO2sat['P4']
x5 = DFO2sat['P5']
x6 = DFO2sat['P6']
x7 = DFO2sat['P7']
x8 = DFO2sat['P8']
x9 = DFO2sat['P9']
x10 = DFO2sat['P10']
x11 = DFO2sat['P11']
x12 = DFO2sat['P12']
x13 = DFO2sat['P13']
x14 = DFO2sat['P14']
x15 = DFO2sat['P15']
plt.ylim(80,110) # Limite en en Y
plt.axhline(y=90, xmin=0, color= 'red') # Maximo normal de presión arterial
plt.axhline(y=100, xmin=0, color= 'red') # Minimo normal de presión arterial

plt.plot(x1, color="b",label="P1", lw="1", marker='o', ms=5, mfc='b')
plt.plot(x2, color="g",label="P2", lw="1", marker='o', ms=5, mfc='g')
plt.plot(x3, color="r",label="P3", lw="1", marker='o', ms=5, mfc='r')
plt.plot(x4, color="c",label="P4", lw="1", marker='o', ms=5, mfc='c' )
plt.plot(x5, color="m",label="P5", lw="1", marker='o', ms=5, mfc='m')
plt.plot(x6, color="y",label="P6", lw="1", marker='o', ms=5, mfc='y' )
plt.plot(x7, color="k",label="P7", lw="1", marker='o', ms=5, mfc='k')

#plt.plot(x9, color="blue", lw="1", marker='o', ms=10, mfc='red')
#plt.plot(x10, color="blue", lw="1", marker='o', ms=10, mfc='red' )
#plt.plot(x11, color="blue", lw="1", marker='o', ms=10, mfc='red')
#plt.plot(x12, color="blue", lw="1", marker='o', ms=10, mfc='red')
#plt.plot(x13, color="blue", lw="1", marker='o', ms=10, mfc='red')
#plt.plot(x14, color="blue", lw="1", marker='o', ms=10, mfc='red' )
#plt.plot(x15, color="blue", lw="1", marker='o', ms=10, mfc='red')

plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

fig = plt.figure(figsize=(15,15))
fig.tight_layout()
plt.ylabel('Escala') # Titulo Y
plt.xlabel('Horas') # Titulo X
plt.title("HR") # Titulo grafica

x1 = DFHR['P1']
x2 = DFHR['P2']
x3 = DFHR['P3']
x4 = DFHR['P4']
x5 = DFHR['P5']
x6 = DFHR['P6']
x7 = DFHR['P7']
x8 = DFHR['P8']
x9 = DFHR['P9']
x10 = DFHR['P10']
x11 = DFHR['P11']
x12 = DFHR['P12']
x13 = DFHR['P13']
x14 = DFHR['P14']
x15 = DFHR['P15']
plt.axhline(y=60, xmin=0, color= 'red') # Maximo normal de presión arterial
plt.axhline(y=100, xmin=0, color= 'red') # Minimo normal de presión arterial

plt.plot(x9, color="b", lw="1", marker='o', ms=5, mfc='b')
plt.plot(x10, color="g", lw="1", marker='o', ms=5, mfc='g')
plt.plot(x11, color="r", lw="1", marker='o', ms=5, mfc='r')
plt.plot(x12, color="c", lw="1", marker='o', ms=5, mfc='c' )
plt.plot(x13, color="m", lw="1", marker='o', ms=5, mfc='m')
plt.plot(x14, color="y", lw="1", marker='o', ms=5, mfc='y' )
plt.plot(x15, color="k", lw="1", marker='o', ms=5, mfc='k')
plt.plot(x8, color="w", lw="1", marker='o', ms=5, mfc='w' )
#plt.plot(x9, color="blue", lw="1", marker='o', ms=10, mfc='red')
#plt.plot(x10, color="blue", lw="1", marker='o', ms=10, mfc='red' )
#plt.plot(x11, color="blue", lw="1", marker='o', ms=10, mfc='red')
#plt.plot(x12, color="blue", lw="1", marker='o', ms=10, mfc='red')
#plt.plot(x13, color="blue", lw="1", marker='o', ms=10, mfc='red')
#plt.plot(x14, color="blue", lw="1", marker='o', ms=10, mfc='red' )
#plt.plot(x15, color="blue", lw="1", marker='o', ms=10, mfc='red')

x