# -*- coding: utf-8 -*-
"""Graficas Sepsis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VxsU3dfHp25DtAxZlBwu-iM--W04oQXP
"""

import pandas as pd

csv_path = "/content/sample_data/SepsisResult.csv"
datos = pd.read_csv(csv_path, sep=',')

print(datos)

datos2 = datos[['SepsisLabel', 'Sepsis_SIRS', 'Sepsis_SOFA']].copy() 

 print(datos2)

import matplotlib.pyplot as plt
import numpy as np

#Analisis HR PACIENTES con Sepsis

#Caracteristicas del grafico

fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("SepsisLabel") # Titulo grafica

plt.hist(datos2['SepsisLabel'],label= 'SepsisLabel',color = 'green')
#plt.hist(datos2['Sepsis_SIRS'],label= 'Sepsis_SIRS', color = 'yellow')
#plt.hist(datos2['Sepsis_SOFA'],label= 'Sepsis_SOFA', color = 'CYAN')


#Mostrar leyenda, cuadricula y figura

plt.legend()
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

#Analisis HR PACIENTES con Sepsis

#Caracteristicas del grafico

fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("Sepsis-SIRS") # Titulo grafica

#plt.hist(datos2['SepsisLabel'],label= 'SepsisLabel',color = 'green')
plt.hist(datos2['Sepsis_SIRS'],label= 'Sepsis_SIRS', color = 'yellow')
#plt.hist(datos2['Sepsis_SOFA'],label= 'Sepsis_SOFA', color = 'CYAN')


#Mostrar leyenda, cuadricula y figura

plt.legend()
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

#Analisis HR PACIENTES con Sepsis

#Caracteristicas del grafico

fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("Sepsis-SOFA") # Titulo grafica

#plt.hist(datos2['SepsisLabel'],label= 'SepsisLabel',color = 'green')
#plt.hist(datos2['Sepsis_SIRS'],label= 'Sepsis_SIRS', color = 'yellow')
plt.hist(datos2['Sepsis_SOFA'],label= 'Sepsis_SOFA', color = 'CYAN')


#Mostrar leyenda, cuadricula y figura

plt.legend()
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

#Analisis HR PACIENTES con Sepsis

#Caracteristicas del grafico

fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("[SepsisLabel y Sepsis-SIRS]") # Titulo grafica

plt.hist(datos2['SepsisLabel'],label= 'SepsisLabel',color = 'green')
plt.hist(datos2['Sepsis_SIRS'],label= 'Sepsis_SIRS', color = 'yellow')
#plt.hist(datos2['Sepsis_SOFA'],label= 'Sepsis_SOFA', color = 'CYAN')


#Mostrar leyenda, cuadricula y figura

plt.legend()
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

#Analisis HR PACIENTES con Sepsis

#Caracteristicas del grafico

fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("[SepsisLabel y Sepsis_SOFA]") # Titulo grafica

plt.hist(datos2['SepsisLabel'],label= 'SepsisLabel',color = 'green')
#plt.hist(datos2['Sepsis_SIRS'],label= 'Sepsis_SIRS', color = 'yellow')
plt.hist(datos2['Sepsis_SOFA'],label= 'Sepsis_SOFA', color = 'CYAN')


#Mostrar leyenda, cuadricula y figura

plt.legend()
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

#Analisis HR PACIENTES con Sepsis

#Caracteristicas del grafico

fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("[Sepsis_SIRS y Sepsis_SOFA]") # Titulo grafica

#plt.hist(datos2['SepsisLabel'],label= 'SepsisLabel',color = 'green')
plt.hist(datos2['Sepsis_SIRS'],label= 'Sepsis_SIRS', color = 'yellow')
plt.hist(datos2['Sepsis_SOFA'],label= 'Sepsis_SOFA', color = 'CYAN')


#Mostrar leyenda, cuadricula y figura

plt.legend()
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

#Analisis HR PACIENTES con Sepsis

#Caracteristicas del grafico

fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("[SepsisLabel - Sepsis_SIRS - Sepsis_SOFA]") # Titulo grafica

plt.hist(datos2['SepsisLabel'],label= 'SepsisLabel',color = 'green')
plt.hist(datos2['Sepsis_SIRS'],label= 'Sepsis_SIRS', color = 'yellow')
plt.hist(datos2['Sepsis_SOFA'],label= 'Sepsis_SOFA', color = 'CYAN')


#Mostrar leyenda, cuadricula y figura

plt.legend()
plt.grid()
plt.show()

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt


fig = plt.figure(figsize=(10,10))
fig.tight_layout()


plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("[SepsisLabel]") # Titulo grafica

sns.countplot(datos2['SepsisLabel'], palette = 'ocean')

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("[Sepsis_SIRS]") # Titulo grafica

sns.countplot(datos2['Sepsis_SIRS'], palette = 'ocean')

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt


fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("[Sepsis_SOFA]") # Titulo grafica


sns.countplot(datos2['Sepsis_SOFA'], palette = 'ocean')

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt


fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("[SepsisLabel - Sepsis_SIRS]") # Titulo grafica

sns.countplot(datos2['SepsisLabel'], palette = 'ocean')
sns.countplot(datos2['Sepsis_SIRS'], palette = 'Oranges')

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt


fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("[SepsisLabel - Sepsis_SOFA]") # Titulo grafica

sns.countplot(datos2['SepsisLabel'], palette = 'ocean')
sns.countplot(datos2['Sepsis_SOFA'], palette = 'Oranges')

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt


fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("[Sepsis_SIRS - Sepsis_SOFA]") # Titulo grafica

sns.countplot(datos2['Sepsis_SOFA'], palette = 'ocean')
sns.countplot(datos2['Sepsis_SIRS'], palette = 'Oranges')

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt


fig = plt.figure(figsize=(10,10))
fig.tight_layout()

plt.ylabel('Cantidad') # Titulo Y
plt.xlabel('Grupo') # Titulo X
plt.title("[SepsisLabel - Sepsis_SIRS - Sepsis_SOFA]") # Titulo grafica

sns.countplot(datos2['Sepsis_SIRS'], palette = 'Pastel1')
sns.countplot(datos2['Sepsis_SOFA'], palette = 'ocean')
sns.countplot(datos2['Sepsis_SIRS'], palette = 'Oranges')

